### ISSUE TITLE
figure tag

### ISSUE THREAD

**Issue by aastudio** [opattison/jekyll-figure-image-tag#4]
Really nice plugin, thanks.

Regarding the [HTML5 semantic](http://html5doctor.com/the-figure-figcaption-elements/), if there's only one image to display and no caption, the```<figure>``` tag shouldn't be used.

Means, this
```
<figure>
  <img src="image.jpg" alt="">
</figure>
```
should be written like this :
```
  <img src="image.jpg" alt="">
```

<br><br>

So I suggest to add this to the plugin :

```
if @class
  figure = "<figure class=\"#{@class}\">"
elsif @caption
  figure = "<figure>"
else
  figure = ""
end

figure += "<img src=\"#{@src}\" alt=\"#{@alt}\"/>"

if @caption
  figure += "<figcaption>#{@caption}</figcaption>"
  figure += "</figure>"
elsif @class
  figure += "</figure>"
else
  figure += ""
end
```

Sorry for my poor english !

**Comment by opattison** [comment]
Unfortunately I have to close this as I’m not going to continue maintaining the repo in the near future. Since I’m not regularly using the plugin it’s unlikely I’ll be coming back to update it.
